package com.splittrip.backend.dto;

import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class CreateGuestUserRequest {
    
    @NotBlank(message = "Guest ID is required")
    private String guestId;  // Generated by frontend and stored in localStorage
    
    @NotBlank(message = "Name is required")
    private String name;
}
